---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/gk_settings":
    get:
      summary: list gk_settings
      responses:
        '200':
          description: successful
  "/api/gk_settings/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    patch:
      summary: update gk_setting
      responses:
        '200':
          description: successful
    put:
      summary: update gk_setting
      responses:
        '200':
          description: successful
  "/api/law_types":
    get:
      summary: list law_types
      responses:
        '200':
          description: successful
    post:
      summary: create law_type
      responses:
        '200':
          description: successful
  "/api/law_types/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    patch:
      summary: update law_type
      responses:
        '200':
          description: successful
    put:
      summary: update law_type
      responses:
        '200':
          description: successful
    delete:
      summary: delete law_type
      responses:
        '200':
          description: successful
  "/api/laws":
    get:
      summary: list laws
      responses:
        '200':
          description: successful
    post:
      summary: create law
      responses:
        '200':
          description: successful
  "/api/laws/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show law
      responses:
        '200':
          description: successful
    delete:
      summary: delete law
      responses:
        '200':
          description: successful
  "/api/quantities":
    get:
      summary: list quantities
      responses:
        '200':
          description: successful
    post:
      summary: create quantity
      responses:
        '200':
          description: successful
  "/api/quantities/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show quantity
      responses:
        '200':
          description: successful
    patch:
      summary: update quantity
      responses:
        '200':
          description: successful
    put:
      summary: update quantity
      responses:
        '200':
          description: successful
    delete:
      summary: delete quantity
      responses:
        '200':
          description: successful
  "/api/represents":
    get:
      summary: list represents
      responses:
        '200':
          description: successful
    post:
      summary: create represent
      responses:
        '200':
          description: successful
  "/api/represents/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show represent
      responses:
        '200':
          description: successful
    patch:
      summary: update represent
      responses:
        '200':
          description: successful
    put:
      summary: update represent
      responses:
        '200':
          description: successful
    delete:
      summary: delete represent
      responses:
        '200':
          description: successful
  "/api/signup":
    post:
      summary: create user
      responses:
        '200':
          description: successful
  "/api/login":
    post:
      summary: login user
      responses:
        '200':
          description: successful
  "/api/profile":
    put:
      summary: show user
      responses:
        '200':
          description: successful
  "/api/update":
    post:
      summary: update user
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:5000/
