---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/gk":
    get:
      summary: list gk
      tags:
      - GK
      responses:
        '200':
          description: successful
        '500':
          description: server error
  "/api/gk/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show GK
      tags:
      - GK
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful
        '404':
          description: not found
        '500':
          description: server error
    patch:
      summary: update GK
      tags:
      - GK
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: successful
        '404':
          description: not found
        '422':
          description: unprocessable entity
        '500':
          description: server error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                gk:
                  type: object
                  properties:
                    gk_name:
                      type: string
                    color:
                      type: string
  "/api/law_types":
    get:
      summary: list law types
      tags:
      - Law Types
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful
        '500':
          description: server error
    post:
      summary: create law type
      tags:
      - Law Types
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: created
        '422':
          description: unprocessable entity
        '500':
          description: server error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                law_type:
                  type: object
                  properties:
                    type_name:
                      type: string
                    color:
                      type: string
                  required:
                  - type_name, color
  "/api/law_types/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show law type
      tags:
      - Law Types
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful
        '404':
          description: not found
        '500':
          description: server error
    put:
      summary: update law type
      tags:
      - Law Types
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: successful
        '404':
          description: not found
        '422':
          description: unprocessable entity
        '500':
          description: server error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                law_type:
                  type: object
                  properties:
                    type_name:
                      type: string
                    color:
                      type: string
    delete:
      summary: delete law type
      tags:
      - Law Types
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful
        '404':
          description: not found
        '500':
          description: server error
  "/api/laws":
    get:
      summary: list laws
      tags:
      - Laws
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful
        '500':
          description: server error
    post:
      summary: create law
      tags:
      - Laws
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: created
        '422':
          description: unprocessable entity
        '500':
          description: server error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                law:
                  type: object
                  properties:
                    law_name:
                      type: string
                    first_element:
                      type: integer
                    second_element:
                      type: integer
                    third_element:
                      type: integer
                    fourth_element:
                      type: integer
                    id_type:
                      type: integer
                  required:
                  - law_name
                  - first_element
                  - second_element
                  - third_element
                  - fourth_element
                  - id_type
  "/api/laws/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show law
      tags:
      - Laws
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful
        '404':
          description: not found
        '500':
          description: server error
    patch:
      summary: update law
      tags:
      - Laws
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: successful
        '404':
          description: not found
        '422':
          description: unprocessable entity
        '500':
          description: server error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                law:
                  type: object
                  properties:
                    law_name:
                      type: string
                    id_type:
                      type: integer
    delete:
      summary: delete law
      tags:
      - Laws
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful
        '404':
          description: not found
        '500':
          description: server error
  "/api/lt":
    get:
      summary: list lt
      tags:
      - LT
      responses:
        '200':
          description: successful
        '500':
          description: server error
  "/api/quantities":
    get:
      summary: list quantities
      tags:
      - Quantities
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful
        '500':
          description: server error
    post:
      summary: create quantity
      tags:
      - Quantities
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: created
        '422':
          description: unprocessable entity
        '500':
          description: server error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: object
                  properties:
                    value_name:
                      type: string
                    symbol:
                      type: string
                    m_indicate_auto:
                      type: integer
                    l_indicate_auto:
                      type: integer
                    t_indicate_auto:
                      type: integer
                    i_indicate_auto:
                      type: integer
                    unit:
                      type: string
                    l_indicate:
                      type: integer
                    t_indicate:
                      type: integer
                    id_gk:
                      type: integer
                  required:
                  - value_name
                  - symbol
                  - m_indicate_auto
                  - l_indicate_auto
                  - t_indicate_auto
                  - i_indicate_auto
                  - unit
                  - l_indicate
                  - t_indicate
                  - id_gk
  "/api/quantities/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show quantity
      tags:
      - Quantities
      responses:
        '200':
          description: successful
        '404':
          description: not found
        '500':
          description: server error
    put:
      summary: update quantity
      tags:
      - Quantities
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: successful
        '404':
          description: not found
        '422':
          description: unprocessable entity
        '500':
          description: server error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: object
                  properties:
                    value_name:
                      type: string
                    symbol:
                      type: string
                    m_indicate_auto:
                      type: integer
                    l_indicate_auto:
                      type: integer
                    t_indicate_auto:
                      type: integer
                    i_indicate_auto:
                      type: integer
                    unit:
                      type: string
                    l_indicate:
                      type: integer
                    t_indicate:
                      type: integer
                    id_gk:
                      type: integer
                  required:
                  - value_name
                  - symbol
                  - m_indicate_auto
                  - l_indicate_auto
                  - t_indicate_auto
                  - i_indicate_auto
                  - unit
                  - l_indicate
                  - t_indicate
                  - id_gk
    delete:
      summary: delete quantity
      tags:
      - Quantities
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful
        '404':
          description: not found
        '500':
          description: server error
  "/api/layers/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: get quantities by lt id
      tags:
      - Quantities
      responses:
        '200':
          description: successful
        '404':
          description: not found
        '500':
          description: server error
  "/api/represents":
    get:
      summary: list represents
      tags:
      - Represents
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful
        '500':
          description: server error
    post:
      summary: create represent
      tags:
      - Represents
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: created
        '422':
          description: unprocessable entity
        '500':
          description: server error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                represent:
                  type: object
                  properties:
                    title:
                      type: string
                    active_quantities:
                      type: array
                      items:
                        type: integer
                  required:
                  - title
                  - active_quantities
  "/api/represents/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show represent
      tags:
      - Represents
      responses:
        '200':
          description: successful
        '404':
          description: not found
        '500':
          description: server error
    put:
      summary: update represent
      security:
      - bearerAuth: []
      tags:
      - Represents
      parameters: []
      responses:
        '200':
          description: successful
        '404':
          description: not found
        '422':
          description: unprocessable entity
        '500':
          description: server error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                represent:
                  type: object
                  properties:
                    title:
                      type: string
                    active_quantities:
                      type: array
                      items:
                        type: integer
    delete:
      summary: delete represent
      tags:
      - Represents
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful
        '404':
          description: not found
        '500':
          description: server error
  "/api/active_view":
    get:
      summary: get active quantities for represent view
      tags:
      - Represents
      responses:
        '200':
          description: successful
  "/api/active_view/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: get active quantities for specific represent view
      tags:
      - Represents
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful
        '404':
          description: not found
  "/api/users/login":
    post:
      summary: user login
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
  "/api/users/register":
    post:
      summary: user register
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
  "/api/users/profile":
    get:
      summary: show user profile
      tags:
      - Users
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful
  "/api/users/update":
    patch:
      summary: update user
      tags:
      - Users
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                last_name:
                  type: string
                first_name:
                  type: string
                patronymic:
                  type: string
  "/api/users/delete":
    delete:
      summary: delete user
      tags:
      - Users
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful
        '404':
          description: not found
  "/api/users/{id}/confirm":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    - name: confirmation_token
      in: query
      description: confirmation token
      required: true
      schema:
        type: string
    post:
      summary: confirm email
      tags:
      - Users
      responses:
        '200':
          description: email confirmed
        '422':
          description: invalid confirmation token
  "/api/users/reset":
    post:
      summary: Send reset password email
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: email sent
        '401':
          description: email not confirmed
        '404':
          description: user not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                  required:
                  - email
  "/api/users/{id}/new_password":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    - name: confirmation_token
      in: query
      description: confirmation token
      required: true
      schema:
        type: string
    get:
      summary: generate and send new password
      tags:
      - Users
      responses:
        '200':
          description: new password generated and sent
        '422':
          description: invalid reset token
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:5000/
