---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/gk_settings":
    get:
      summary: list gk_settings
      responses:
        '200':
          description: successful
  "/api/gk_settings/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    patch:
      summary: update gk_setting
      responses:
        '200':
          description: successful
    put:
      summary: update gk_setting
      responses:
        '200':
          description: successful
  "/api/law_types":
    get:
      summary: list law_types
      responses:
        '200':
          description: successful
    post:
      summary: create law_type
      responses:
        '200':
          description: successful
  "/api/law_types/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    patch:
      summary: update law_type
      responses:
        '200':
          description: successful
    put:
      summary: update law_type
      responses:
        '200':
          description: successful
    delete:
      summary: delete law_type
      responses:
        '200':
          description: successful
  "/api/laws":
    get:
      summary: list laws
      responses:
        '200':
          description: successful
    post:
      summary: create law
      responses:
        '200':
          description: successful
  "/api/laws/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show law
      responses:
        '200':
          description: successful
    delete:
      summary: delete law
      responses:
        '200':
          description: successful
  "/api/quantities":
    post:
      summary: create quantity
      tags:
      - Quantities
      parameters: []
      responses:
        '201':
          description: created
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                val_name:
                  type: string
                symbol:
                  type: string
                M_indicate:
                  type: integer
                L_indicate:
                  type: integer
                T_indicate:
                  type: integer
                I_indicate:
                  type: integer
                unit:
                  type: string
                l_indicate:
                  type: integer
                t_indicate:
                  type: integer
                g_indicate:
                  type: integer
                k_indicate:
                  type: integer
              required:
              - val_name
              - symbol
              - M_indicate
              - L_indicate
              - T_indicate
              - I_indicate
              - unit
              - l_indicate
              - t_indicate
              - g_indicate
              - k_indicate
    get:
      summary: list quantities
      tags:
      - Quantities
      responses:
        '200':
          description: successful
        '500':
          description: server error
  "/api/quantities/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show quantity
      tags:
      - Quantities
      responses:
        '200':
          description: successful
        '404':
          description: not found
    put:
      summary: update quantity
      tags:
      - Quantities
      parameters: []
      responses:
        '200':
          description: successful
        '404':
          description: not found
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                val_name:
                  type: string
                symbol:
                  type: string
                M_indicate:
                  type: integer
                L_indicate:
                  type: integer
                T_indicate:
                  type: integer
                I_indicate:
                  type: integer
                unit:
                  type: string
                l_indicate:
                  type: integer
                t_indicate:
                  type: integer
                g_indicate:
                  type: integer
                k_indicate:
                  type: integer
    delete:
      summary: delete quantity
      tags:
      - Quantities
      responses:
        '200':
          description: successful
        '404':
          description: not found
  "/api/represents":
    get:
      summary: list represents
      responses:
        '200':
          description: successful
    post:
      summary: create represent
      responses:
        '200':
          description: successful
  "/api/represents/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show represent
      responses:
        '200':
          description: successful
    patch:
      summary: update represent
      responses:
        '200':
          description: successful
    put:
      summary: update represent
      responses:
        '200':
          description: successful
    delete:
      summary: delete represent
      responses:
        '200':
          description: successful
  "/api/login":
    post:
      summary: login
      tags:
      - Users
      parameters:
      - name: email
        in: query
        required: true
        schema:
          type: string
      - name: password
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
  "/api/users":
    post:
      summary: create user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                last_name:
                  type: string
                first_name:
                  type: string
                patronymic:
                  type: string
              required:
              - email
              - password
              - last_name
              - first_name
              - patronymic
  "/api/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      tags:
      - Users
      responses:
        '200':
          description: successful
    put:
      summary: update user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                last_name:
                  type: string
                first_name:
                  type: string
                patronymic:
                  type: string
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
- bearerAuth: []
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:5000/
