---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/quantities":
    get:
      summary: list quantities
      responses:
        '200':
          description: successful
    post:
      summary: create quantity
      responses:
        '200':
          description: successful
  "/api/quantities/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show quantity
      responses:
        '200':
          description: successful
    patch:
      summary: update quantity
      responses:
        '200':
          description: successful
    put:
      summary: update quantity
      responses:
        '200':
          description: successful
    delete:
      summary: delete quantity
      responses:
        '200':
          description: successful
  "/api/represents":
    get:
      summary: list represents
      responses:
        '200':
          description: successful
    post:
      summary: create represent
      responses:
        '200':
          description: successful
  "/api/represents/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show represent
      responses:
        '200':
          description: successful
    patch:
      summary: update represent
      responses:
        '200':
          description: successful
    put:
      summary: update represent
      responses:
        '200':
          description: successful
    delete:
      summary: delete represent
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:5000/
