---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/cell/{cellId}":
    parameters:
    - name: cellId
      in: path
      description: cellId
      required: true
      schema:
        type: string
    get:
      summary: get_quantity_by_cell_id lt
      responses:
        '200':
          description: successful
  "/api/represents":
    get:
      summary: list represents
      responses:
        '200':
          description: successful
    post:
      summary: create represent
      responses:
        '200':
          description: successful
  "/api/represents/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show represent
      responses:
        '200':
          description: successful
    patch:
      summary: update represent
      responses:
        '200':
          description: successful
    put:
      summary: update represent
      responses:
        '200':
          description: successful
    delete:
      summary: delete represent
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000/
